### ISSUE TITLE
Next updates

### ISSUE THREAD

**Issue by tatunts** [bozbez/win-capture-audio#1]
Hello!

First of all, thank you very much for your work, this is an amazing plugin.

I would like to suggest a couple of enhancements for the next versions, if you think that's possible :)

1. Easy to extract releases for portable OBS instances: it would be great if the final zip archive available in the releases section, a zip file that we could just extract to the portable installation, with the correct `data` and `obs-plugins` folders inside. 
2. Integrate with the native game capture source: not sure if possible or if it could break something, but, would be great if we could use the same source for capturing both the game image and audio, for example.

Thanks!

**Comment by bozbez** [comment]
Hi, and thanks for the kind words.

1. Should be easy enough, was planning to make an installer based on ISS or similar which should make that easier
2. Opened a new issue for this: #5

**Comment by bozbez** [comment]
Installer done, have a look at the [latest release](https://github.com/bozbez/win-capture-audio/releases/tag/v1.0.0-alpha.2). Also includes a (manually extracting) zip archive with the correct directory structure to extract for portable installations.
