### ISSUE TITLE
Not all windows appearing in the plugin

### ISSUE THREAD

**Issue by actualcdeveloper** [bozbez/win-capture-audio#115]
So for some reason, not all the windows appear in the list of selectable sources. So far I've noticed this with Spotify and Discord (which are the ones I want to use it for, funny). Firefox is showing fine, and I'm writing this after a fresh install of the plugin. OBS up-to-date, Windows as well. However I am running Windows 10 (also updated, last update like a day ago or such).

**Comment by bozbez** [comment]
They won't appear until they open an audio session to actually play audio, which might not happen until you try to play a song etc. Once you have selected them, they will be re-hooked without problem.

Additions such as manual entry of executable names are being considered for future versions.
