### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by pablobongiolatti** [bozbez/win-capture-audio#121]
Hi, my obs vs is 21.2.0, i tried installing the latest (v.2.2.2 beta) and didn't work, when i open my sources and try to add "Application audio output capture", the thing is not there, please help?

**Comment by pablobongiolatti** [comment]
Extra info: tried with v2.2.2, v.2.2.1, v2.2.0, and the folder where it installs is the default obs-studio

**Comment by benlei** [comment]
I tried https://github.com/bozbez/win-capture-audio/releases/tag/v2.1.0-beta and it seems to work. 2.2.2 didn't, though.
