### ISSUE TITLE
No audio being captured by plugin.

### ISSUE THREAD

**Issue by vyressi** [bozbez/win-capture-audio#125]
I get the mixer entry and I am able to select a process, but I get no audio, regardless of which process, or whether I use inclusive or exclusive.

Running latest OBS in a clean install on latest windows revision.

The older WASPI version works fine, but causes issues.

This issue is agnostic to the audio device.

I have pulled down and built the application at https://github.com/microsoft/windows-classic-samples/tree/main/Samples/ApplicationLoopback that appears to use the same API and it works fine. no matter what process I throw it at.

Here is an OBS log

[2022-02-27 16-52-27.txt](https://github.com/bozbez/win-capture-audio/files/8149506/2022-02-27.16-52-27.txt)

Please advise on troubleshooting steps.

**Comment by Master-Liu-TBF** [comment]
I had the same problem, but for each audio capture source(s), you have to add the source for each i.e. I added discord and under properties i added discord as an executable. I hope this helps as it took me a moment to figure it out.

**Comment by CamHallulis** [comment]
I'm having the same issue. Worked flawlessly yesterday. Now...Nothing

**Comment by vyressi** [comment]
> I had the same problem, but for each audio capture source(s), you have to add the source for each i.e. I added discord and under properties i added discord as an executable. I hope this helps as it took me a moment to figure it out.

As I indicated in my original post, I have added executables under the properties.  While I appreciate the sentiment, not having an executable added to the plugin is not the issue I am having.

**Comment by Riotline** [comment]
> This issue is agnostic to the audio device.
Some cases of having certain audio playing on different audio output devices can simply not function as intended. I've had a case where I'm using elgato wave virtual outputs and specific apps in specific outputs would not function as intended. 
Please attempt changing audio device outputs (then remaking the source for the application in OBS) to verify it is not being affected by this issue.

**Comment by TugT4G** [comment]
I am having the same exact issue for 2.2.2 so I switched back to 2.1 and now it is recording my audio device. There is something wrong when choosing your audio device.

For example, when I play Minecraft Java Edition there is only an option to choose javaw.exe and no option to choose the window via the audio source's properties. The GUI is different and is definitely missing the "Window" option to make it work.

So 2.2.2 Audio Source>Properties needs to be addressed I am assuming unless there is some other setting that is placed elsewhere.

**Comment by Master-Liu-TBF** [comment]
> I had the same problem, but for each audio capture source(s), you have to add the source for each i.e. I added discord and under properties i added discord as an executable. I hope this helps as it took me a moment to figure it out.

Well, I was wrong, I had thoguht that I had it figured out, and unless i have selected default audio source no audio will be picked up. But the question is how do I uninstall the 2.2 or can I just install the 2.1?

**Comment by TugT4G** [comment]
@Master-Liu-TBF I just installed it manually. Just move the appropriate files over and just replace what is already there. I compared what was in 2.2 and 2.1 and it's the same amount of files as each other. 2.1 has worked flawlessly with my OBS and my brother's.

**Comment by Master-Liu-TBF** [comment]
> @Master-Liu-TBF I just installed it manually. Just move the appropriate files over and just replace what is already there. I compared what was in 2.2 and 2.1 and it's the same amount of files as each other. 2.1 has worked flawlessly with my OBS and my brother's.

So I just unistalled 2.2 and all of its components, and just installed 2.1 and yup, works fine.

**Comment by TugT4G** [comment]
> So I just unistalled 2.2 and all of its components, and just installed 2.1 and yup, works fine.

Awesome, glad it worked out. 2.2 is definitely missing a setting when adding audio. I haven't tried any other version in between 2.1 and 2.2.

This plugin is awesome and it definitely needs to be built into OBS. Many kudos to bozbez for putting time into this.

**Comment by Thndr** [comment]
Windows 10 Pro 21H2 Build 19044
Asus B550-F ROG Strix
AMD Ryzen 5 5600X
Latest Bios and audio(realtek)/chipset drivers from the motherboard manufacturer

OBS 27.2.4 (64bit) - Normal install, Portable mode install, and Steam version.

I've tested with multiple installs and even tested with the latest drivers on my PC, still doesn't capture any audio.
I do notice that on 2.1.0 it has some notable differences:

EXE selection shows titles of the programs/windows in 2.1.0, but not 2.2.0+
The audio mixer only shows 1 channel for 2.2.0+, but both channels for 2.1.0

**Comment by vyressi** [comment]
As OBS 28 deprecates this repo I'm going to close this request
