### ISSUE TITLE
Version 2.2.2 Crashes OBS Studio

### ISSUE THREAD

**Issue by MrTeeXD** [bozbez/win-capture-audio#146]
### OBS Version
Using Version 27.2.4 64bit Portable Version

### Operating System & Version
Windows 10 64bit running Version 21H1 Build 19043.1620

### OBS Studio Crash Logs
https://obsproject.com/logs/_uaV6mSnZjjDEW8z

### Steps to reproduce the issue
1: Open OBS Studio and any Program
2: Add a Application Audio Capture source
3: Add your desired executable from the dropdown menu
4: Close OBS Studio but leave the added executable open
5: Reopen OBS Studio and OBS should close.

### What is expected to happen?
OBS Studio would open normally when the added executable is added in the plugin without crashing OBS Studio immediately.

**Comment by Bezrayy** [comment]
same here

**Comment by walker-WSH** [comment]
It seems to be same with mine, crashed while calling `ActivateAudioInterfaceAsync()`. 
But it only appeared once on my PC.

![4350dbaf-ce4c-4eb0-beb6-cc5513784fa1](https://user-images.githubusercontent.com/18413354/161230636-e305c54e-4819-487b-a976-ed00931ce955.png)

**Comment by MrTeeXD** [comment]
I took the plugin out of OBS due to it crashing OBS and wrecking my streams.

**Comment by Machliah** [comment]
https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e this could be a fix

**Comment by MrTeeXD** [comment]
Merging with #123
