### ISSUE TITLE
Do this plugin for Linux! Please!!

### ISSUE THREAD

**Issue by seriousfreezing** [bozbez/win-capture-audio#147]

**Comment by BuyMyMojo** [comment]
As far as I know this uses a specific feature added in later versions of windows. it would require a complete feature rewrite to support linux, two if you want to support Pulse Audio and PipeWire

**Comment by TheBlueBurger** [comment]
@seriousfreezing wouldn't a jack capture work fine with qjackctl?

**Comment by DwarfFighterCleric** [comment]
This is not needed for Linux.  
All you have to do is create a separate Sink in pulseaudio (you can create as many sinks you want)  
You can either do it manually with terminal commands  
or you can automated it directly (making it load when you run pulseaudio -k to re-initialize)  
by putting the command directly in /etc/pulse/default.pa  
  
Just google "create pulseaudio sink" and you're good to go. Easy. (one of the very few things that Linux actually makes easier to do, unfortunately)

**Comment by BuyMyMojo** [comment]
> This is not needed for Linux. All you have to do is create a separate Sink in pulseaudio (you can create as many sinks you want) You can either do it manually with terminal commands or you can automated it directly (making it load when you run pulseaudio -k to re-initialize) by putting the command directly in /etc/pulse/default.pa
> 
> Just google "create pulseaudio sink" and you're good to go. Easy. (one of the very few things that Linux actually makes easier to do, unfortunately)

To be fair creating a Sink is a pain in the ass compared to the plugin so I understand wanting this plugin in linux

**Comment by seriousfreezing** [comment]
I understand, thank you for giving me an alternative. But I still think it is NOTHING compared to the delight of this plugin when recording! Even if you have the possibility to do the same effect by commands in Linux, nothing compares to the convenience and ease of using this plugin.

**Comment by bozbez** [comment]
For Linux you should almost certainly use a Pulse/PipeWire multi-sink setup. If you are looking for something to automate this for you then look elsewhere, this plugin is extremely Windows specific and anything providing similar functionality on Linux would require an entirely different implementation.

**Comment by Avasam** [comment]
You can use https://github.com/dimtpap/obs-pipewire-audio-capture, as far as I can tell, it's working the exact same way as this plugin (can do "all apps except some"). But for linux
