### ISSUE TITLE
Making a compatibility list

### ISSUE THREAD

**Issue by BuyMyMojo** [bozbez/win-capture-audio#19]
I'm making a list, will probably format a markdown version or something or maybe a github page for the repo itself down the line. sharing what I have so far before I head to bed.

The list: https://docs.google.com/spreadsheets/d/1L6-MVYwCI6Gk4nJT_9eALFaB4ZAqPLljefmqXnFu8Ys/edit?usp=sharing

**Comment by bozbez** [comment]
Since with the new architecture application specific failures have not really been seen and aren't expected, I think we can close this - thanks for the effort creating the list for version 1.

**Comment by BuyMyMojo** [comment]
glad to help, loving the plugin so far :)
