### ISSUE TITLE
Only captures Spotify sometimes

### ISSUE THREAD

**Issue by BuyMyMojo** [bozbez/win-capture-audio#2]
Issues:
Only captures spotify is a song is already playing, if song is paused for too long it will not capture audio when resumes and when transitioning to a new song it stops capturing after a couple seconds(cross fade on)

Gif:
![Spotify weird stuff](https://user-images.githubusercontent.com/46948241/129649538-7af9cdbc-f710-4877-9057-38109ee0f247.gif)

**Comment by bozbez** [comment]
An issue with both the internal hook state machine and the window selection logic.
Should be fixed with 57a722ea40ca1ee5bf2343c5c5b6c09899ce44c4 and cafd24a404fcb20a434c31ed4b01f41a5260f87b.

**Comment by BuyMyMojo** [comment]
Do you have a build your can share please?

**Comment by bozbez** [comment]
https://github.com/bozbez/win-capture-audio/releases/tag/v1.0.0-alpha.2
