### ISSUE TITLE
You cannot select a sound from the OBS

### ISSUE THREAD

**Issue by BazZziliuS** [bozbez/win-capture-audio#216]
Due to the fact that it is impossible to select a sound from the OBS, the sound alerts of donations or subscriptions are not heard on the stream

obs version: 28.0.2
win-capture-audio: v2.2.3-beta

**Comment by dualsquire** [comment]
did you found a solution to this ??

**Comment by BazZziliuS** [comment]
> did you found a solution to this ??

yes
https://github.com/obsproject/obs-studio/issues/7468#issuecomment-1257864337
