### ISSUE TITLE
Plugin isn't capturing the audio

### ISSUE THREAD

**Issue by 0ember1** [bozbez/win-capture-audio#24]
After I downloaded zip file, and copied files from it to obs root directory, Application Audio Output Capture" source appeared, but when i tried to test it and captured my browser, i saw that the plugin isn't working. As shown in image, my desktop audio captures browser audio pretty easily, but plugin is just not working. I tried to reinstall the obs 2 times, tried with plugin installer app, nothing helps. How can I fix it?
![8biWPYhTGW](https://user-images.githubusercontent.com/71174607/131135029-0d5131c5-0d7c-4281-8a42-3572e312cdc3.png)
![изображение](https://user-images.githubusercontent.com/71174607/131134989-3cb07c2f-31eb-4605-8b71-fc6538ed60f2.png)

**Comment by bozbez** [comment]
No further info provided so closing.
