### ISSUE TITLE
weird "crackling" noises after a few hours

### ISSUE THREAD

**Issue by ttvSakuria** [bozbez/win-capture-audio#257]
hey there,

me and a few other streamers seem to have weird audio issues after 4-ish hours of streaming/recording. game and music sources are starting to get crackling/static noises. mic sound is absolutely fine, just the rest of the audio seems to be screwed up. i would love to have this issue resolved since this plugin is a lifesaver ♥ (it works fine without the plugin)

cheers!

**Comment by scorthyn** [comment]
same here, is this still being maintained?

**Comment by scorthyn** [comment]
btw this is fixed in the lastest version, OBS version RC1.
