### ISSUE TITLE
SEVERE memory leak

### ISSUE THREAD

**Issue by codeHusky** [bozbez/win-capture-audio#263]
The other night I was streaming with several win-capture-audio sources on OBS 30.0.2. As usual, the audio sources began to crackle around an hour or two into stream so I had to hide and then show them all again. However, few more hours into stream and my PC began to lag significantly. 

Upon checking with ProcExp64, obs64.exe was using over 10,000,000 K "private bytes" (10gb) of memory while the working set was only around 2-3GB (typical for my setup). 
This memory allocation seems to increase constantly over time with no real purpose, far exceeding the amount of memory the application is actually using. Restarting OBS resolved the issue and freed up the memory for other applications.

**Comment by codeHusky** [comment]
![IMG_6342](https://github.com/bozbez/win-capture-audio/assets/6946558/a85871ad-af42-44e8-8232-e02e2cd53d6d)
Here’s an example of what it looks like in ProcExp, happened after 5.25 hours of streaming

**Comment by cD1rtX3** [comment]
Are you sure that's a problem with the plugin and not a problem with OBS itself?

**Comment by codeHusky** [comment]
> Are you sure that's a problem with the plugin and not a problem with OBS itself?

I've done long recordings on separate profiles that use the plugin less or not at all, and I've been able to do those recordings for extended periods without negative consequences. I haven't strictly tested to eliminate some OBS issue as a factor, but I'm not doing anything too special with OBS either. If it was an OBS issue I'm sure it would've been a huge issue by now.

**Comment by codeHusky** [comment]
Following a stream yesterday for 4 hours, I can confirm that not using win-capture-audio yields a maximum memory usage of private bytes of around 770k on my system rather than 110mil. Most definitely an issue with this plugin

**Comment by codeHusky** [comment]
just to clarify this issue seems to be an underlying OBS issue, not sure what's causing it yet though as it happened w/out plugins
