### ISSUE TITLE
Does not automatically show on Audio Mixer

### ISSUE THREAD

**Issue by Riotline** [bozbez/win-capture-audio#29]
Windows 10 Pro 10.0.19043 Build 19043

Having an issue with the source not appearing on the Audio Mixer unless I toggle "Hide from Mixer" on and off.
I'm utilising studio mode, so I add the source then push it to program. 
And since it doesn't show, I do the above method then re-push to program.

**Comment by Riotline** [comment]
For me, this occurs every time I add the application audio source so I don't have any specific steps for replication.

**Comment by bozbez** [comment]
So this happens with the built in Audio Output Capture as well, so I can only assume this is either the intended behaviour of studio mode or a bug in OBS rather than this plugin (unless I'm missing something).

**Comment by Riotline** [comment]
> So this happens with the built in Audio Output Capture as well, so I can only assume this is either the intended behaviour of studio mode or a bug in OBS rather than this plugin (unless I'm missing something).

Can confirm Audio Output Capture automatically goes to Audio Mixer when pushed to program, so not the case.

**Comment by bozbez** [comment]
Well that's weird, the mixer wasn't updating at all for me and then I relaunched and it seems to work fine... https://streamable.com/o0v5ph

**Comment by Riotline** [comment]
I'll attempt at using a fresh install just in case other plugins or scripts are interfering.

**Comment by Riotline** [comment]
I should also that in #30, I posted a link to a video showing a different issue and in that video it shows that the audio source in the mixer does not disappear when the source is not in the scene. On top of that, sometimes when the application sound source is not in a scene, you are still able to hear it; other times, it is fine.

**Comment by Riotline** [comment]
Problem Identified. Use of Studio Mode alongside an enabled "Duplicate Sources" (disabled by default) option will cause the Application Audio Source to not appear properly. Disable Duplicate Sources if you have it enabled.
