### ISSUE TITLE
Discord severe gaps and glitchiness

### ISSUE THREAD

**Issue by Riotline** [bozbez/win-capture-audio#30]
Windows 10 Pro 10.0.19043 Build 19043

Discord audio capture seemed to have some weird glitchiness after some time of use. It slowly become worse as time progressed (not sure if that could be syncing issues?) but I had to swap back to Desktop Audio after I was notified of the issue. Note that sound was just fine through Desktop Audio and through my headphones. Even in OBS, the audio meter showed everything was fine. Even another source (Overwatch) was doing fine.

It got worse when transitioning through scenes so potentially this could be the culprit?

Shown here: https://www.twitch.tv/videos/1135794206?t=00h09m53s

**Comment by bozbez** [comment]
Looks the same as #21, #22 and maybe #31.
This shouldn't be happening and is hopefully resolvable, but I am generally lacking time to work on this at the moment.

**Comment by Riotline** [comment]
#31 sounds really close but can't completely verify.
Linked is me testing with spotify and youtube where I have a scene with Spotify only, and Spotify + Chrome.
As you can see, the chrome audio meter appears to also not line up with what's actually coming through after the YouTube video is paused.
The audio glitchiness appears to occur on any app. Although haven't verified it is based of Electron or chromium rendering.
https://youtu.be/ya4TDaMMEfw

**Comment by bozbez** [comment]
Thanks for the video, acts as a good reference.
Already tested Windows 11, same issues seemed to happen.
