### ISSUE TITLE
Application Audio not picking up any sound

### ISSUE THREAD

**Issue by jackdudek5150** [bozbez/win-capture-audio#41]
![OBS audio screenshot 1](https://user-images.githubusercontent.com/83737782/135192029-9ac30a94-d03a-4739-b652-8ad577f1d66b.jpg)
I have just recently installed the plugin along with multiple friends to record multitrack audio separating game audio from discord, except neither of them are being picked up even though I have the right window and track selected while there is sound being output by those applications. My friends who downloaded this at the same time have had none of these issues despite setting it up the same way, and I have OBS fully updated and have tried restarting it. Is there a bug, or something obvious that I'm missing?

**Comment by bozbez** [comment]
Update your windows, and post the OBS log if that doesn't work.

**Comment by jackdudek5150** [comment]
Update didn't change anything, here is the current log file after trying again and creating a new audio source with the same properties. I really hope it's not some stupid tiny thing I'm missing here, thanks for the help.
https://obsproject.com/logs/zGV6OgqiVO42vu9q

**Comment by bozbez** [comment]
You still need more Windows updates. They might take a few days to show up if you recently did a feature update.
