### ISSUE TITLE
Valorant sends chat audio out on a different process?

### ISSUE THREAD

**Issue by BuyMyMojo** [bozbez/win-capture-audio#42]
It seems Valorant sends out VOIP to another process? No other option appears in the list so you might need to look into it, if you can make it a separate option tho that could be useful but still any team chat is better then none lmao

two videos with team chat but no team chat audio:
https://athenascope.com/game-session/13768255/video/374040025
https://athenascope.com/game-session/13768255/video/374040287

**Comment by bozbez** [comment]
Does it show up twice in Windows volume mixer/app volume device settings?

**Comment by BuyMyMojo** [comment]
there is another process called the "riot client" that I cannot change the volume of in the list

**Comment by hebenji** [comment]
I also have the same issue. When separating the audio it will only capture the in game and not the voice comms. I checked everything made sure its only the right input and outputs and still doesn't work and usually putting it back to default should work but it doesn't work. Since I have an elgato wave link I don't have the problem, all I have to do is route it to my game source. But those that doesnt, when routing the voice chat to either headset or just in default it doesn't pick it up in obs. Not sure if its actually a bug or you actually need like a virtual cable like voicemeeter

**Comment by richardmeyer** [comment]
Would Love a fix for warzone as well

**Comment by r0senove** [comment]
yes the voip not captured

**Comment by izzy** [comment]
I have a similar problem where I can't capture audio from executables that have been spawned by other programs but don't have a UI. They don't show up in the list and thus can't be captured. They show up in window's volume mixer tho.

Any chance on a fix for this?

**Comment by ash-development** [comment]
i also have this issue with valorant.

**Comment by ash-development** [comment]
@bozbez

**Comment by BuyMyMojo** [comment]
> @bozbez

They will see it and fix it when they have the time, don't need to ping them again in their own repo

**Comment by ash-development** [comment]
> > @bozbez
> 
> They will see it and fix it when they have the time, don't need to ping them again in their own repo

well they haven't commented in 4-5 ish months so i figured id send them a notif 🤷

**Comment by bozbez** [comment]
Whatever executable is outputting the audio should now be selectable in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta). Note that it might not appear until someone actually voice-comms, but one you select it then it should re-hook just fine.

**Comment by BuyMyMojo** [comment]
I was wondering why I got a bunch of emails from this repo. new update hype!

**Comment by MnFeN** [comment]
I don't play those games above, but I met similar problem.
The TTS (text to sound) plugin and voice chat plugin were not detected in the list. 
**This problem was fixed by entering the actual name of the programs.**

**Comment by LilBill24th** [comment]
Solved the issue: when you add the program "VALORANT-Win64-Shipping.exe" you need to add the "RiotClientServices.exe" as well.  It might not show up right away but it should relatively shortly after installation
![Win-Capture Error Fix](https://user-images.githubusercontent.com/103705172/163499438-3c0a0ba2-6901-42e1-8a71-2ee086cb3b63.PNG)
.

**Comment by ash-development** [comment]
> Solved the issue: when you add the program "VALORANT-Win64-Shipping.exe" you need to add the "RiotClientServices.exe" as well. It might not show up right away but it should relatively shortly after installation ![Win-Capture Error Fix](https://user-images.githubusercontent.com/103705172/163499438-3c0a0ba2-6901-42e1-8a71-2ee086cb3b63.PNG) .

yeah the developer added this as an update awhile ago...
https://github.com/bozbez/win-capture-audio/issues/42#issuecomment-1037233662

**Comment by Ryancav2** [comment]
Would Warzone be basically the same thing?
