### ISSUE TITLE
About timing of add new win-capture-audio source in Audio Mixer

### ISSUE THREAD

**Issue by ZereInt** [bozbez/win-capture-audio#43]
Hello.
First of all, thanks for create really good plugin. And sorry of my english low level.

obs: 27.1.3
win-capture-audio v2.0.0-beta.3
windows 10 Pro 21H1 (os build 19043.1266)

I found out this situation in my desktop.

1. push plus(+) button in Sources tab
2. Add source win-capture-audio source normally
3. Even if see audio mixer tab, can't see volume controller of new win-capture-audio source
4. shutdown obs, and re-execute
5. can see new source of win-capture-audio in mixer tab

Is it the normal? or abnormal?
Thanks for reading.

**Comment by bozbez** [comment]
#29?

**Comment by ZereInt** [comment]
@bozbez 
I found a occurring when checked duplicate scene button in studio mode.
and don't occur after unchecked duplicate scene button.

Thanks for your help. #29
