### ISSUE TITLE
Crash if you change the scene profile

### ISSUE THREAD

**Issue by eilsgames** [bozbez/win-capture-audio#51]
Idk why but if you change the scene profile obs crash

**Comment by bozbez** [comment]
Couldn't reproduce... could you confirm this only happens with the plugin installed, and post your OBS log and crash logs?
Also give the latest version (v2.1.0-beta) a shot, it changes some of the error handling.

**Comment by eilsgames** [comment]
> Couldn't reproduce... could you confirm this only happens with the plugin installed, and post your OBS log and crash logs? Also give the latest version (v2.1.0-beta) a shot, it changes some of the error handling.

It's rare cause i could reproduce it only when i change first the profile and then the scene profile
[2021-11-01 09-52-04.txt](https://github.com/bozbez/win-capture-audio/files/7453359/2021-11-01.09-52-04.txt)

**Comment by bozbez** [comment]
This was probably cause by a few awkward deadlocks... should be fixed in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).

**Comment by eilsgames** [comment]
It keeps happening in the lastest version
