### ISSUE TITLE
plugin not picking up audio

### ISSUE THREAD

**Issue by knightmare013** [bozbez/win-capture-audio#52]
i downloaded the plugin via .exe file and the plugin does't seem to pick anything up, i'm new to obs and streaming so i don't quite have enough knowledge to know the problem myself.
wanted to be able to have separate audio tracks with the plugin so i didn't need anything external
![image](https://user-images.githubusercontent.com/93467669/139574582-085733cd-5f7b-4bfb-aa92-8dbc564b22f9.png)

**Comment by bozbez** [comment]
Update Windows.
