### ISSUE TITLE
OBS Hang when exit

### ISSUE THREAD

**Issue by LeonWong93** [bozbez/win-capture-audio#53]
OBS Hang when Exit/Close OBS
issue happen when application that need to capture/hook is not running
if application that used to capture/hook is running, Exit/Close OBS won't hang..

i do notice that v2.1.0 beta released,
so base on the desciption,
i remove all v2.0.0 beta 3 source,
uninstall plugin (i use exe installer),
install new v2.1.0 beta version plugin (exe installer),
add source and select capture Discord,
exit OBS, no hang because discord is running..
exit Discord, open OBS, exit OBS, OBS Hang..

checked winver, i on Windows 10 Pro x64 version 2004 OS Build 19041.1288

*Problem exist when using v2.0.0 Beta 3

when OBS is hang while exit, and i force it to close without waiting for respond (which wait for respond 1 hours still hanging)
the log is look like this
01:54:36.603: ==== Shutting down ==================================================
01:54:36.826: WASAPI: Device 'XV340CK P (NVIDIA High Definition Audio)' Terminated
01:54:36.835: WASAPI: Device 'Headset Microphone (Oculus Virtual Audio Device)' Terminated
01:54:38.047: WASAPI: Device 'Microphone (Yeti X WoW Edition)' Terminated

when OBS success Exit properly, the log file is like this
01:56:19.772: ==== Shutting down ==================================================
01:56:20.030: WASAPI: Device 'XV340CK P (NVIDIA High Definition Audio)' Terminated
01:56:20.037: WASAPI: Device 'Headset Microphone (Oculus Virtual Audio Device)' Terminated
01:56:21.423: WASAPI: Device 'Microphone (Yeti X WoW Edition)' Terminated
01:56:22.882: [audio-capture: 'unknown'] (audio_capture_worker_tick) shutting down
01:56:22.888: All scene data cleared
01:56:22.888: ------------------------------------------------
*** and lot of usual info below **

**Comment by LeonWong93** [comment]
i updated to Win10 21H1, problem still exist..

**Comment by flipdamusic** [comment]
Can also reproduce this issue. OBS hangs on closing. Sometime also i have stuttering in Audio Capture. Switching to another scene or click anywhere results also in a hung up.

**Comment by Johnnyblu84** [comment]
I also have this issue

**Comment by bozbez** [comment]
Should be fixed in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).

**Comment by SashaCurry** [comment]
December 2025, last version app, problem is actual
