### ISSUE TITLE
SWTOR doesn't work

### ISSUE THREAD

**Issue by Talfereg** [bozbez/win-capture-audio#54]
It can capture SWTOR audio if I check the box to get all other sound except the current window, but The Old Repblic sounds do not come though using normal window capture method. Game coding issue? DirectX issue? My other games work :D and this has been really awesome to use with discord and rocket league for tournaments.

**Comment by Tenebrosful** [comment]
I got the same issue.

- I'm on `Windows 11 21H2`
- Delete an audio source from `swtor.exe` freeze OBS
- With `swtor.exe` and `Pick all except the source` there is no audio
- When you take a random audio source and select `Pick all except the source` we can have SWTOR's audio

I hope that can be fix from plugin side.

**Comment by Tenebrosful** [comment]
I don't know if we can add more infos to help

**Comment by bozbez** [comment]
Should be able to select whatever process the audio is actually coming from in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).
