### ISSUE TITLE
SNDCPY not showing 

### ISSUE THREAD

**Issue by linuxmobile** [bozbez/win-capture-audio#55]
I've got a problem. SNDCPY is using vlc.exe in background. Then it isn't a window. That's why win-capture-audio can't recognize vlc as audio source. But the audio is working perfect.

I want to know how to add vlc.exe if it's not showing as window.

![image](https://user-images.githubusercontent.com/10554636/139682457-27c956c0-27fb-43f6-ad70-5d2667e48568.png)

**Comment by mochaaP** [comment]
You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.

<https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25>

**Comment by linuxmobile** [comment]
> 
> 
> You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25

I will try, thx u

**Comment by mochaaP** [comment]
Please use JACK instead.

**Comment by linuxmobile** [comment]
> 
> 
> Please use JACK instead.

i haven't jack :(

**Comment by mochaaP** [comment]
@linuxmobile <https://jackaudio.org/>

cc @bozbez I guess we can close this?

**Comment by alkaris2** [comment]
Why bother with JACK when you can use Pipewire and PulseAudio. You can already control the volumes directly from the audio panel simply by right-clicking and adjusting the audio for the applications there. Albeit not the most efficient way for controlling audio of applications streaming into OBS, and would be nice if you got that kind of audio control going into OBS for an already existing feature to plug in to.

**Comment by cire467** [comment]
> You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25

Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?

**Comment by mochaaP** [comment]
> > You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> > [rom1v/sndcpy@`f0995ca`/sndcpy.bat#L25](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25)
> 
> Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?

You need to install sndcpy on your Android device and forward the port to your machine first.
(Or remove [this line](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L20) from the script.)

**Comment by cire467** [comment]
> > > You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> > > [rom1v/sndcpy@`f0995ca`/sndcpy.bat#L25](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25)
> > 
> > 
> > Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?
> 
> You need to install sndcpy on your Android device and forward the port to your machine first. 

I have installed sndcpy APK to my Android device, ran the batch script and got the audio from my Android to PC working, but nothing happens if i used media source and inserted the address in OBS.

> (Or remove [this line](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L20) from the script.)

I removed the line you said from the script in sndcpy.bat and in sndcpy file. What do I do next?

**Comment by IKYIM** [comment]
> > > You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> > > [rom1v/sndcpy@`f0995ca`/sndcpy.bat#L25](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25)
> > 
> > 
> > Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?
> 
> You need to install sndcpy on your Android device and forward the port to your machine first. (Or remove [this line](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L20) from the script.)

Hello, are you still there? I am very desperate to get this working and I would pay you if you can help me get this to work. I've been messing around different methods but can't seem to make it work. If you accept, we can talk in Discord.

**Comment by mochaaP** [comment]
> > > > You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> > > > [rom1v/sndcpy@`f0995ca`/sndcpy.bat#L25](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25)
> > > 
> > > 
> > > Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?
> > 
> > 
> > You need to install sndcpy on your Android device and forward the port to your machine first. (Or remove [this line](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L20) from the script.)
> 
> Hello, are you still there? I am very desperate to get this working and I would pay you if you can help me get this to work. I've been messing around different methods but can't seem to make it work. If you accept, we can talk in Discord.

@IKYIM Feel free to mail me! ;)

<mailto:hello@mochaa.ws>

**Comment by IKYIM** [comment]
> > > > > You can add `sndcpy`'s output as a media source manually, which listens on `tcp://localhost:28200` by default.
> > > > > [rom1v/sndcpy@`f0995ca`/sndcpy.bat#L25](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25)
> > > > 
> > > > 
> > > > Hello, sorry for jumping in an old discussion but it doesn't work in my end. All I have to do is add media source, untick local and add the address, correct?
> > > 
> > > 
> > > You need to install sndcpy on your Android device and forward the port to your machine first. (Or remove [this line](https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L20) from the script.)
> > 
> > 
> > Hello, are you still there? I am very desperate to get this working and I would pay you if you can help me get this to work. I've been messing around different methods but can't seem to make it work. If you accept, we can talk in Discord.
> 
> @IKYIM Feel free to mail me! ;)
> 
> [mailto:hello@mochaa.ws](mailto:hello@mochaa.ws)

@mochaaP Messaged you on email.

**Comment by bozbez** [comment]
Should be solved by [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).
