### ISSUE TITLE
Audiosource shows up in mixer, and shows there is sound, but does not record game sound

### ISSUE THREAD

**Issue by YourLocalViking** [bozbez/win-capture-audio#59]
Was trying to stream RS2V whilst listening to some music that I didn't want to stream. Whilst in the audio mixer it shows that it is picking up the game audio, it is not showing up on stream.

**Comment by bozbez** [comment]
If it shows levels in the audio mixer but not on stream that is an issue with your OBS setup. Check your track configuration.
