### ISSUE TITLE
Unable to record audio even though tracks are selected?

### ISSUE THREAD

**Issue by caseyjames95** [bozbez/win-capture-audio#63]
I did my first recording today and everything worked perfect on stream but did give audio in recording. Game/Discord did not pass through to recording. Only my Mic.

**Comment by HaggardCar7790** [comment]
I noticed when I was messing around with it today that it seems like only one "Application Audio Output Capture" source will work at a time, and they only work when I specify the exact window instead of trying to use the hotkey. Is this what is happening for you?

**Comment by bozbez** [comment]
This is either what @HaggardCar7790 said or an issue with your OBS/audio track setup.
