### ISSUE TITLE
OBS STOPS WORKING WHEN SELECT FOREGROUND HOTKEY

### ISSUE THREAD

**Issue by Predy1** [bozbez/win-capture-audio#69]
When i installed version 2.1.0-beta and go in properties on app output and select on mode capture foreground window with specific hotkey my obs stops working
![obs  stops](https://user-images.githubusercontent.com/95125691/143677154-da807363-8f44-4972-a56a-8bf0d42a8e95.png)

**Comment by walker-WSH** [comment]
It seems be fixed in https://github.com/bozbez/win-capture-audio/pull/78

can you have a try with latest code ?

**Comment by bozbez** [comment]
Should be fixed in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).
