### ISSUE TITLE
Firefox doesn't get captured

### ISSUE THREAD

**Issue by mruks** [bozbez/win-capture-audio#72]
I recently changed browser to use firefox and sadly discovered it doesn't get captured. Even though it's an available option, no sound comes through.

**Comment by walker-WSH** [comment]
Now I tested the latest code, firefox can be captured normally

**Comment by mruks** [comment]
Awesome when is the new version available?

**Comment by bozbez** [comment]
[v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).
