### ISSUE TITLE
Crash at IAudioCaptureClient::ReleaseBuffer often

### ISSUE THREAD

**Issue by walker-WSH** [bozbez/win-capture-audio#79]
I often meet crash at IAudioCaptureClient::ReleaseBuffer and do not know the reason.
By the way, I never meet this crash happen in win-wasapi even it also use WASAPI.

It seems be caused by MS's code.
**Any other meet this crash ?**

![1639361239](https://user-images.githubusercontent.com/18413354/145743334-d3ee435d-8f21-4584-a2a3-d09dd7b9defc.png)
![1639361249](https://user-images.githubusercontent.com/18413354/145743347-af96bcd6-6710-4b1e-ab42-87b20bf3ff38.png)

**Comment by bozbez** [comment]
One thing to try would be to move the `obs_source_output_audio()` call out of the buffer locked region, perhaps this call is taking too long and the Windows audio engine can't handle it?

**Comment by walker-WSH** [comment]
> One thing to try would be to move the `obs_source_output_audio()` call out of the buffer locked region, perhaps this call is taking too long and the Windows audio engine can't handle it?

It can't be caused by taking too long between GetBuffer() and ReleaseBuffer().
If it is, we can reproduce it easy by sleeping some time. However, it happens randomly.

**Comment by bozbez** [comment]
Hmm does this crash happen with v2.0.0-beta.3? The only other oddity about these calls is that we are doing them on some MF workqueue thread. For v2.0.0-beta.3 if it crashes it would show up as something like "audio-capture-helper.exe exited with code 4324262134) as the helper process crashes.

With the annoyances with the crash on exit bug it might be time to just ditch the MF queues since they seem to noticeably improve stability to begin with.

**Comment by walker-WSH** [comment]
> Hmm does this crash happen with v2.0.0-beta.3? The only other oddity about these calls is that we are doing them on some MF workqueue thread. For v2.0.0-beta.3 if it crashes it would show up as something like "audio-capture-helper.exe exited with code 4324262134) as the helper process crashes.
> 
> With the annoyances with the crash on exit bug it might be time to just ditch the MF queues since they seem to noticeably improve stability to begin with.

I am using latest code, instead of v2.0.0-beta.3.
If you think I should have a test on v2.0.0-beta.3, I can install it to vetify.
By the way, this crash never happen every time.

**Comment by bozbez** [comment]
Yeah give v2.0.0-beta.3 a test if you can.

**Comment by walker-WSH** [comment]
> Yeah give v2.0.0-beta.3 a test if you can.

I can have a test with v2.beta. But in the past days, this crash no longer happen on my PC.
So I can't ensure the test result of v.2.beta is correct.

**Comment by bozbez** [comment]
Got rid of the MF queues in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta), and I don't know of anyone else to encounter this... reopen if it still happens.
