### ISSUE TITLE
Full volume when sending via NDI

### ISSUE THREAD

**Issue by DweEroz** [bozbez/win-capture-audio#83]
Hi again :)

New issue found, if this can help: when I set a new audio source, and add the NDI Filter, no matter the volume of the Audio Mixer, it will be played at full volume on the streaming PC. 

A clue that makes me think that it is related to Win Capture Audio — and not to the NDI plugin itself — is that the volume of the original NDI source changes according to the volume of the Gaming PC, while the Win Capture Audio sources stay maxed out.

Gaming PC, with the source reduced so that it outputs at around -45dB: ![image](https://user-images.githubusercontent.com/49686576/145838733-83e3c8bb-0886-41f3-845d-20fd89d0913f.png)

Streaming PC, with said source, dedicated NDI audio (first one) vs the original NDI output, taking all the audio sources (second one):
 ![Capture d’écran 2021-12-13 163127](https://user-images.githubusercontent.com/49686576/145841189-7e856c7a-830f-4181-8117-29bed004bc56.png)

I obviously remain available if I need more information, details or tests 🙂 

Thank you again for this plugin!!!

**Comment by IonicEcko** [comment]
This isn't related to the plugin but is instead how the NDI plugin works.

When you use the inbuilt NDI "source", NDI is sending the active scene including all filters etc. When you add a specific NDI output via filter to an audio source it excludes other filters, volumes etc on that source.

This isn't something the plugin can or should change, unless I'm misunderstanding.

**Comment by DweEroz** [comment]
You're absolutely right: your comment made me try from another source, and I was able to reproduce the problem, since it is associated with the OBS NDI plugin, and the filter itself. Guess that only Palakis can do something, thanks again!
